### ISSUE TITLE
Errors in the building of the base index

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#242]
Doesn't seem to be breaking, but I'm getting a lot of error output in the logs from the base index
`ERROR 2022-05-31 20:34:15,173 urls 9 140100021253888 Unexpected error 9: ['Traceback (most recent call last):\n', '  File "/ars/tr_sys/tr_sys/urls.py", line 82, in base_index\n    data[\'entries\'].append(req.build_absolute_uri(reverse(item.name)))\n', "AttributeError: 'URLResolver' object has no attribute 'name'\n"]
ERROR 2022-05-31 20:34:15,173 urls 9 140100777248512 Unexpected error 9: ['Traceback (most recent call last):\n', '  File "/ars/tr_sys/tr_sys/urls.py", line 82, in base_index\n    data[\'entries\'].append(req.build_absolute_uri(reverse(item.name)))\n', "AttributeError: 'URLResolver' object has no attribute 'name'\n"]
ERROR 2022-05-31 20:34:15,173 urls 9 140100787738368 Unexpected error 9: ['Traceback (most recent call last):\n', '  File "/ars/tr_sys/tr_sys/urls.py", line 82, in base_index\n    data[\'entries\'].append(req.build_absolute_uri(reverse(item.name)))\n', "AttributeError: 'URLResolver' object has no attribute 'name'\n"]
ERROR 2022-05-31 20:34:15,173 urls 9 140100021253888 Unexpected error 9: ['Traceback (most recent call last):\n', '  File "/ars/tr_sys/tr_sys/urls.py", line 82, in base_index\n    data[\'entries\'].append(req.build_absolute_uri(reverse(item.name)))\n', "AttributeError: 'URLResolver' object has no attribute 'name'\n"]
ERROR 2022-05-31 20:34:15,174 urls 9 140100787738368 Unexpected error 9: ['Traceback (most recent call last):\n', '  File "/ars/tr_sys/tr_sys/urls.py", line 82, in base_index\n    data[\'entries\'].append(req.build_absolute_uri(reverse(item.name)))\n', "AttributeError: 'URLResolver' object has no attribute 'name'\n"]`

**Comment by MarkDWilliams** [comment]
This issue has been fixed
